title: Linked IT
description: Azure managed services, cloud security posture, and governance insights.
url: "https://linkeddominic.github.io"
baseurl: "/linkeditblogsite"
timezone: Australia/Sydney

permalink: /blog/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Linked IT

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
